import pyautogui
from geometry_utils import normalize_points
import os
import json

# --- SETUP ---
HOST, PORT = '0.0.0.0', 5005
FILE_PORT = 5006
DISCOVERY_PORT = 37020
REVERSE_PORT = 6000       # PC → Phone commands
REVERSE_ACK_PORT = 6001   # Phone → PC heartbeats/responses

# --- SECURITY SETUP (Dynamic Keys) ---
# Keys are loaded from pairing_keys.json (generated by QR pairing).
# Falls back to hardcoded defaults if file doesn't exist yet.
USE_ENCRYPTION = True

_PAIRING_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pairing_keys.json")

def _load_keys():
    """Load keys from pairing file, or use defaults."""
    defaults = {
        "aes_key": "my_secret_16byte",
        "hmac_key": "my_hmac_secret_key",
        "secret_key": "my_super_secret_project_key"
    }
    if os.path.exists(_PAIRING_FILE):
        try:
            with open(_PAIRING_FILE, 'r') as f:
                data = json.load(f)
                return {
                    "aes_key": data.get("aes_key", defaults["aes_key"]),
                    "hmac_key": data.get("hmac_key", defaults["hmac_key"]),
                    "secret_key": data.get("secret_key", defaults["secret_key"]),
                }
        except Exception:
            pass
    return defaults

_keys = _load_keys()
AES_KEY = _keys["aes_key"]
HMAC_KEY = _keys["hmac_key"]
SECRET_KEY = _keys["secret_key"]

# Optimized PyAutoGUI settings
pyautogui.FAILSAFE, pyautogui.PAUSE = False, 0  

# --- GLOBAL STATE ---
# Shared between commands.py (writer) and services.py (reader)
preview_active = False

# --- REDEFINED TEMPLATES (Resampled) ---
V_SHAPE_TEMPLATE = normalize_points([(0, 0), (50, 100), (100, 0)])
S_SHAPE_TEMPLATE = normalize_points([(100, 0), (0, 0), (0, 100), (100, 100)])
L_BRACKET = normalize_points([(100, 0), (0, 50), (100, 100)])  # < (Back 5s)
R_BRACKET = normalize_points([(0, 0), (100, 50), (0, 100)])   # > (Forward 5s)
# O - Circle: For Refreshing a page
CIRCLE_TEMPLATE = normalize_points([
    (50, 0), (85, 15), (100, 50), (85, 85), 
    (50, 100), (15, 85), (0, 50), (15, 15), (50, 0)
])
# ^ - Caret: For Maximizing a window
CARET_TEMPLATE = normalize_points([(0,100), (50,0), (100,100)])

# M - Shape: For Minimizing all windows (Show Desktop)
M_SHAPE_TEMPLATE = normalize_points([(0,100), (25,0), (50,100), (75,0), (100,100)])
